# Generated by Django 2.1.15 on 2020-05-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(db_column='#', primary_key=True, serialize=False, unique=True, verbose_name='#')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='등록일')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='수정일')),
                ('content', models.TextField(blank=True, db_column='content', null=True, verbose_name='내용')),
            ],
            options={
                'verbose_name': '덧글',
                'verbose_name_plural': '덧글',
                'db_table': 'g_comment',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(db_column='#', primary_key=True, serialize=False, unique=True, verbose_name='#')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='등록일')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='수정일')),
                ('status', models.SmallIntegerField(choices=[(0, '완료'), (1, '처리'), (2, '보류')], default=0, verbose_name='status')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='제목')),
                ('content', models.TextField(blank=True, db_column='content', null=True, verbose_name='내용')),
                ('image', models.ImageField(blank=True, db_column='image', null=True, upload_to='blog/image/%Y%m%d/', verbose_name='이미지')),
                ('files', models.FileField(blank=True, db_column='files', null=True, upload_to='blog/file/%Y%m%d/', verbose_name='첨부파일')),
            ],
            options={
                'verbose_name': '블로그',
                'verbose_name_plural': '블로그',
                'db_table': 'g_blog',
            },
        ),
    ]
