# Generated by Django 2.1.15 on 2020-05-05 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200505_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, related_name='작성자', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
