# Generated by Django 2.1.15 on 2020-05-28 05:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200526_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, db_column='content', null=True, verbose_name='내용'),
        ),
    ]
