# Generated by Django 2.1.15 on 2020-05-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200507_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '완료'), (1, '처리'), (2, '보류')], default=0),
        ),
    ]
