# Generated by Django 2.1.15 on 2020-05-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '완료'), (1, '처리'), (2, '보류')], default=0, verbose_name='status'),
        ),
    ]
