# Generated by Django 2.1.15 on 2020-05-26 02:09

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(db_column='#', primary_key=True, serialize=False, unique=True, verbose_name='#')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='등록일')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='modified_at', verbose_name='수정일')),
                ('title', models.CharField(db_column='title', max_length=255, verbose_name='제목')),
                ('content', django_summernote.fields.SummernoteTextField(blank=True, db_column='content', null=True, verbose_name='내용')),
                ('image', models.ImageField(blank=True, db_column='image', null=True, upload_to='blog/image/%Y%m%d/', verbose_name='이미지')),
                ('files', models.FileField(blank=True, db_column='files', null=True, upload_to='blog/file/%Y%m%d/', verbose_name='첨부파일')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'db_table': 'g_notice',
            },
        ),
    ]
