# Generated by Django 2.1.15 on 2020-05-28 05:30

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20200528_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_summernote.fields.SummernoteTextField(blank=True, db_column='content', null=True, verbose_name='내용'),
        ),
    ]
