# Generated by Django 2.1.15 on 2020-05-21 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200521_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(db_column='address', on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='crm.Address', verbose_name='주소'),
        ),
    ]
