# Generated by Django 2.1.15 on 2020-05-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.SmallIntegerField(choices=[(None, '부서 선택'), (0, '경영지원'), (1, '영업'), (2, '1팀'), (3, '2팀')], default=None, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(None, '성별 선택'), (0, '선택하지 않음'), (1, '남성'), (2, '여성')], default=None, verbose_name='gender'),
        ),
    ]
